server:
  port: 28000

tcp:
  server:
    proxy:
      enabled: true
      bind-port: 9999
  client:
    async-connction:
      enabled: true
      host: 127.0.0.1
      port: 5555
      reconnectDelaySec: 10

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true
